//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lua.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Antlr4.Lua {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LuaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface ILuaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChunk([NotNull] LuaParser.ChunkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.chunk"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChunk([NotNull] LuaParser.ChunkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] LuaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] LuaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat0</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat0([NotNull] LuaParser.Stat0Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat0</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat0([NotNull] LuaParser.Stat0Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat1</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat1([NotNull] LuaParser.Stat1Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat1</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat1([NotNull] LuaParser.Stat1Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat2</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat2([NotNull] LuaParser.Stat2Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat2</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat2([NotNull] LuaParser.Stat2Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat3</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat3([NotNull] LuaParser.Stat3Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat3</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat3([NotNull] LuaParser.Stat3Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat4</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat4([NotNull] LuaParser.Stat4Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat4</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat4([NotNull] LuaParser.Stat4Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat5</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat5([NotNull] LuaParser.Stat5Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat5</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat5([NotNull] LuaParser.Stat5Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat6</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat6([NotNull] LuaParser.Stat6Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat6</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat6([NotNull] LuaParser.Stat6Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat7</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat7([NotNull] LuaParser.Stat7Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat7</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat7([NotNull] LuaParser.Stat7Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat8</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat8([NotNull] LuaParser.Stat8Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat8</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat8([NotNull] LuaParser.Stat8Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat9</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat9([NotNull] LuaParser.Stat9Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat9</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat9([NotNull] LuaParser.Stat9Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat10</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat10([NotNull] LuaParser.Stat10Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat10</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat10([NotNull] LuaParser.Stat10Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat11</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat11([NotNull] LuaParser.Stat11Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat11</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat11([NotNull] LuaParser.Stat11Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat12</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat12([NotNull] LuaParser.Stat12Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat12</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat12([NotNull] LuaParser.Stat12Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat13</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat13([NotNull] LuaParser.Stat13Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat13</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat13([NotNull] LuaParser.Stat13Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>stat14</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat14([NotNull] LuaParser.Stat14Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>stat14</c>
	/// labeled alternative in <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat14([NotNull] LuaParser.Stat14Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetstat([NotNull] LuaParser.RetstatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetstat([NotNull] LuaParser.RetstatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] LuaParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] LuaParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncname([NotNull] LuaParser.FuncnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncname([NotNull] LuaParser.FuncnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarlist([NotNull] LuaParser.VarlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarlist([NotNull] LuaParser.VarlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamelist([NotNull] LuaParser.NamelistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamelist([NotNull] LuaParser.NamelistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplist([NotNull] LuaParser.ExplistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.explist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplist([NotNull] LuaParser.ExplistContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp17</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp17([NotNull] LuaParser.Exp17Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp17</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp17([NotNull] LuaParser.Exp17Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp16</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp16([NotNull] LuaParser.Exp16Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp16</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp16([NotNull] LuaParser.Exp16Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp15</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp15([NotNull] LuaParser.Exp15Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp15</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp15([NotNull] LuaParser.Exp15Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp14</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp14([NotNull] LuaParser.Exp14Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp14</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp14([NotNull] LuaParser.Exp14Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp9</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp9([NotNull] LuaParser.Exp9Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp9</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp9([NotNull] LuaParser.Exp9Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp8</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp8([NotNull] LuaParser.Exp8Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp8</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp8([NotNull] LuaParser.Exp8Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp7</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp7([NotNull] LuaParser.Exp7Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp7</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp7([NotNull] LuaParser.Exp7Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp6</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp6([NotNull] LuaParser.Exp6Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp6</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp6([NotNull] LuaParser.Exp6Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp5</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp5([NotNull] LuaParser.Exp5Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp5</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp5([NotNull] LuaParser.Exp5Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp4</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp4([NotNull] LuaParser.Exp4Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp4</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp4([NotNull] LuaParser.Exp4Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp13</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp13([NotNull] LuaParser.Exp13Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp13</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp13([NotNull] LuaParser.Exp13Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp3</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp3([NotNull] LuaParser.Exp3Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp3</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp3([NotNull] LuaParser.Exp3Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp12</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp12([NotNull] LuaParser.Exp12Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp12</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp12([NotNull] LuaParser.Exp12Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp2</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp2([NotNull] LuaParser.Exp2Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp2</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp2([NotNull] LuaParser.Exp2Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp11</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp11([NotNull] LuaParser.Exp11Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp11</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp11([NotNull] LuaParser.Exp11Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp1</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp1([NotNull] LuaParser.Exp1Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp1</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp1([NotNull] LuaParser.Exp1Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp10</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp10([NotNull] LuaParser.Exp10Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp10</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp10([NotNull] LuaParser.Exp10Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>exp0</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp0([NotNull] LuaParser.Exp0Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>exp0</c>
	/// labeled alternative in <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp0([NotNull] LuaParser.Exp0Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixexp([NotNull] LuaParser.PrefixexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixexp([NotNull] LuaParser.PrefixexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctioncall([NotNull] LuaParser.FunctioncallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.functioncall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctioncall([NotNull] LuaParser.FunctioncallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrExp([NotNull] LuaParser.VarOrExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varOrExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrExp([NotNull] LuaParser.VarOrExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] LuaParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] LuaParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarSuffix([NotNull] LuaParser.VarSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarSuffix([NotNull] LuaParser.VarSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameAndArgs([NotNull] LuaParser.NameAndArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nameAndArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameAndArgs([NotNull] LuaParser.NameAndArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] LuaParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] LuaParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctiondef([NotNull] LuaParser.FunctiondefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctiondef([NotNull] LuaParser.FunctiondefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncbody([NotNull] LuaParser.FuncbodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.funcbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncbody([NotNull] LuaParser.FuncbodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParlist([NotNull] LuaParser.ParlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParlist([NotNull] LuaParser.ParlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableconstructor([NotNull] LuaParser.TableconstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableconstructor([NotNull] LuaParser.TableconstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldlist([NotNull] LuaParser.FieldlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.fieldlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldlist([NotNull] LuaParser.FieldlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] LuaParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] LuaParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldsep([NotNull] LuaParser.FieldsepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldsep([NotNull] LuaParser.FieldsepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorOr([NotNull] LuaParser.OperatorOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorOr([NotNull] LuaParser.OperatorOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAnd([NotNull] LuaParser.OperatorAndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorAnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAnd([NotNull] LuaParser.OperatorAndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorComparison([NotNull] LuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorComparison([NotNull] LuaParser.OperatorComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorStrcat([NotNull] LuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorStrcat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorStrcat([NotNull] LuaParser.OperatorStrcatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorAddSub([NotNull] LuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorAddSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorAddSub([NotNull] LuaParser.OperatorAddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorMulDivMod([NotNull] LuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorMulDivMod"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorMulDivMod([NotNull] LuaParser.OperatorMulDivModContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorBitwise([NotNull] LuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorBitwise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorBitwise([NotNull] LuaParser.OperatorBitwiseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorUnary([NotNull] LuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorUnary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorUnary([NotNull] LuaParser.OperatorUnaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorPower([NotNull] LuaParser.OperatorPowerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.operatorPower"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorPower([NotNull] LuaParser.OperatorPowerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] LuaParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] LuaParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] LuaParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] LuaParser.StringContext context);
}
} // namespace Antlr4.Lua
